version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "face-sentiment-dj-5"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-pcatkpeq1n2w"
s3_prefix = "face-sentiment-dj-5"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = ["DionnaFaceSentimentFunction=681261969843.dkr.ecr.us-east-1.amazonaws.com/facesentimentdj4913ae854/dionnafacesentimentfunction08af1c4brepo"]
disable_rollback = true
confirm_changeset = true
